site_name: Biotope
site_description: Biotope - CLI integration for BioCypher ecosystem packages
site_author: Sebastian Lobentanzer
site_url: https://biotope.readthedocs.io/

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:

theme:
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.top
  name: material
  palette:
    - scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Learn:
    - Tutorials:
      - Annotate Omics: learn/tutorials/annotate-omics.md
  - Reference:
      - API Documentation:
          - Annotate: api-docs/annotate.md
          - Build: api-docs/build.md
          - Chat: api-docs/chat.md
          - Init: api-docs/init.md
          - Read: api-docs/read.md
          - View: api-docs/view.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            heading_level: 3

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/biocypher
      name: Sebastian Lobentanzer

copyright: Copyright &copy 2025 Sebastian Lobentanzer

repo_url: https://github.com/biocypher/biotope
repo_name: biocypher/biotope
edit_uri: edit/main/docs

watch:
  - biotope
