"""Write a BioCypher project to disk from compiled mappings and alignment."""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import Any

import yaml

from biotope.croissant.alignment.loader import load_alignment
from biotope.croissant.mapping.loader import load_mapping
from biotope.croissant.mapping.model import Mapping

SCHEMA_CONFIG_HEADER = (
    "# Generated by biocypher-croissant. Reviewed and committed manually.\n"
    "# See https://biocypher.org/BioCypher/schema-config.html for the spec.\n"
)


def _emit_schema_config(mappings: list[Mapping]) -> str:
    """Build a BioCypher ``schema_config.yaml`` snippet from mapping declarations."""
    config: dict[str, dict[str, Any]] = {}
    seen_node_types: set[str] = set()
    seen_edge_types: set[str] = set()

    for mapping in mappings:
        for node in mapping.nodes:
            if node.type in seen_node_types:
                continue
            seen_node_types.add(node.type)
            config[node.type] = {
                "represented_as": "node",
                "input_label": node.type,
                "preferred_id": "id",
                "properties": {p: "str" for p in node.properties},
            }
        for edge in mapping.edges:
            if edge.type in seen_edge_types:
                continue
            seen_edge_types.add(edge.type)
            config[edge.type] = {
                "represented_as": "edge",
                "input_label": edge.type,
                "source": edge.source.from_,
                "target": edge.target.from_,
                "is_a": "association",
                "properties": {p: "str" for p in edge.properties},
            }

    return SCHEMA_CONFIG_HEADER + yaml.safe_dump(config, sort_keys=False)


def _emit_build_script(project_name: str, mapping_paths: list[Path], alignment_path: Path | None) -> str:
    """Build the ``create_knowledge_graph.py`` entry script."""
    aligned = alignment_path is not None
    mapping_paths_repr = ",\n        ".join(repr(str(p.name)) for p in mapping_paths)
    return f'''"""Generated entry point for the {project_name} graph build."""

from pathlib import Path

from biocypher import BioCypher

from biotope.croissant.acquisition import AcquisitionContext
from biotope.croissant.spec import load_from_path
from biotope.croissant.mapping import compile_mapping, load_mapping
{"from biotope.croissant.alignment import load_alignment, merge_adapters" if aligned else ""}


HERE = Path(__file__).parent


def build() -> None:
    bc = BioCypher(
        biocypher_config_path=str(HERE / "config" / "biocypher_config.yaml"),
        schema_config_path=str(HERE / "config" / "schema_config.yaml"),
    )

    mapping_paths = [
        {mapping_paths_repr},
    ]

    adapters = {{}}
    for name in mapping_paths:
        mapping = load_mapping(HERE / "mappings" / name)
        dataset = load_from_path(mapping.croissant)
        context = AcquisitionContext(dataset, datasets_location=Path(mapping.croissant).parent)
        adapter = compile_mapping(mapping, context)
        stem = Path(name).stem.replace(".mapping", "")
        adapters[stem] = adapter

    {"alignment = load_alignment(HERE / 'alignment.yaml')" if aligned else ""}
    {"merged = merge_adapters(adapters, alignment)" if aligned else "merged = next(iter(adapters.values()))"}

    bc.write_nodes(merged.get_nodes())
    bc.write_edges(merged.get_edges())
    bc.write_import_call()


if __name__ == "__main__":
    build()
'''


def materialize_project(
    project_dir: Path,
    mapping_paths: list[Path],
    alignment_path: Path | None = None,
) -> dict[str, str]:
    """Write a runnable BioCypher project to ``project_dir``.

    Layout::

        project_dir/
            config/
                biocypher_config.yaml
                schema_config.yaml
            mappings/
                <one copy of each mapping.yaml>
            alignment.yaml    # if provided
            create_knowledge_graph.py
    """
    project_dir.mkdir(parents=True, exist_ok=True)
    (project_dir / "config").mkdir(exist_ok=True)
    (project_dir / "mappings").mkdir(exist_ok=True)

    mappings = [load_mapping(p) for p in mapping_paths]

    schema_config_path = project_dir / "config" / "schema_config.yaml"
    schema_config_path.write_text(_emit_schema_config(mappings))

    biocypher_config_path = project_dir / "config" / "biocypher_config.yaml"
    if not biocypher_config_path.exists():
        biocypher_config_path.write_text(
            "biocypher:\n"
            "  dbms: csv\n"
            "  log_to_disk: true\n"
            "  output_directory: biocypher-out\n",
        )

    for src in mapping_paths:
        shutil.copy(src, project_dir / "mappings" / src.name)

    written_alignment: Path | None = None
    if alignment_path is not None:
        load_alignment(alignment_path)  # validate
        written_alignment = project_dir / "alignment.yaml"
        shutil.copy(alignment_path, written_alignment)

    script_path = project_dir / "create_knowledge_graph.py"
    script_path.write_text(
        _emit_build_script(
            project_name=project_dir.name,
            mapping_paths=[project_dir / "mappings" / p.name for p in mapping_paths],
            alignment_path=written_alignment,
        ),
    )

    return {
        "project_dir": str(project_dir),
        "schema_config": str(schema_config_path),
        "biocypher_config": str(biocypher_config_path),
        "build_script": str(script_path),
        "alignment": str(written_alignment) if written_alignment else "",
    }
