"""Write a BioCypher project to disk from compiled semantic mappings.

Layout::

    project_dir/
        config/
            biocypher_config.yaml
            schema_config.yaml
        mappings/
            <one copy of each mapping.yaml>
        generated/
            <mapping_stem>/
                __init__.py
                adapter.py
        alignment.yaml    # if provided
        create_knowledge_graph.py

* ``schema_config.yaml`` is generated from the semantic IR (no manual
  authoring). Entities emit ``namespace`` (never ``preferred_id``), and
  ``input_label`` is the mapping key so the adapter↔schema contract is
  autogenerated.
* ``generated/<mapping_stem>/adapter.py`` is a deterministic, inspectable
  Python module that wraps the compiled adapter. Users never edit it; it
  exists for provenance and to make builds debuggable.
* The build is strict: unresolved or legacy mappings are rejected.
"""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import Any

import yaml

from biotope.croissant.alignment.loader import load_alignment
from biotope.croissant.mapping.compile import derive_namespace, derive_schema_term
from biotope.croissant.mapping.loader import load_mapping
from biotope.croissant.mapping.model import (
    Mapping,
    Selector,
)
from biotope.croissant.spec import FieldKind, load_from_path


SCHEMA_CONFIG_HEADER = (
    "# Generated by `biotope build` from semantic mapping files.\n"
    "# Edit the source mapping(s) instead — this file is overwritten on every build.\n"
    "# See https://biocypher.org/BioCypher/schema-config.html for the BioCypher spec.\n"
)


def _emit_schema_config(mappings: list[Mapping]) -> str:
    """Build ``schema_config.yaml`` from a list of compiled :class:`Mapping`."""
    config: dict[str, dict[str, Any]] = {}
    entity_terms: dict[tuple[int, str], str] = {}
    seen_terms: set[str] = set()

    for index, mapping in enumerate(mappings):
        for name, entity in mapping.entities.items():
            schema_term = derive_schema_term(name, entity.schema_term)
            entity_terms[(index, name)] = schema_term
            if schema_term in seen_terms:
                continue
            seen_terms.add(schema_term)
            config[schema_term] = {
                "represented_as": "node",
                "input_label": name,
                "namespace": derive_namespace(mapping, entity),
                "properties": _typed_properties(mapping, entity.record_set, entity.properties),
            }

    for index, mapping in enumerate(mappings):
        for name, relation in mapping.relations.items():
            schema_term = derive_schema_term(name, relation.schema_term)
            if schema_term in seen_terms:
                continue
            seen_terms.add(schema_term)
            source_key = relation.source.entity if relation.source else None
            target_key = relation.target.entity if relation.target else None
            source_term = entity_terms.get((index, source_key), source_key or "")
            target_term = entity_terms.get((index, target_key), target_key or "")
            config[schema_term] = {
                "represented_as": "edge",
                "input_label": name,
                "source": source_term,
                "target": target_term,
                "properties": _typed_properties(mapping, relation.record_set, relation.properties),
            }

    return SCHEMA_CONFIG_HEADER + yaml.safe_dump(config, sort_keys=False)


def _typed_properties(
    mapping: Mapping,
    record_set_name: str | None,
    properties: dict[str, Selector],
) -> dict[str, str]:
    """Map property names to BioCypher type strings, inferred from Croissant fields."""
    if not properties:
        return {}
    if record_set_name is None:
        return {prop: "str" for prop in properties}

    try:
        dataset = load_from_path(mapping.croissant)
    except Exception:
        return {prop: "str" for prop in properties}
    rs = dataset.record_set_by_name(record_set_name)
    if rs is None:
        return {prop: "str" for prop in properties}

    field_kinds: dict[str, FieldKind] = {}
    for f in rs.field:
        try:
            field_kinds[f.name] = f.kind()
        except ValueError:
            continue

    out: dict[str, str] = {}
    for prop_name, selector in properties.items():
        out[prop_name] = _selector_type(selector, mapping, field_kinds)
    return out


def _selector_type(
    selector: Selector,
    mapping: Mapping,
    field_kinds: dict[str, FieldKind],
) -> str:
    if selector.use is not None:
        return "str"
    if selector.transform == "as_curie":
        return "str"
    if selector.field is None or selector.field.startswith("$item"):
        return "str"
    kind = field_kinds.get(selector.field)
    if kind is None:
        return "str"
    if kind == FieldKind.STRUCT:
        msg = f"Struct-valued property field {selector.field!r} is not supported in v1"
        raise ValueError(msg)
    return _BIOCYPHER_TYPES.get(kind, "str")


_BIOCYPHER_TYPES: dict[FieldKind, str] = {
    FieldKind.STRING: "str",
    FieldKind.URL: "str",
    FieldKind.DATE: "str",
    FieldKind.BOOLEAN: "bool",
    FieldKind.INTEGER: "int",
    FieldKind.FLOAT: "float",
    FieldKind.ARRAY: "str[]",
}


# ---------------------------------------------------------------------------
# Generated Python per mapping
# ---------------------------------------------------------------------------


_GENERATED_ADAPTER_TEMPLATE = '''"""Generated adapter for `{stem}` mapping. Do not edit by hand.

This module is rebuilt by `biotope build`. It exists so the build is
inspectable and so each mapping has a stable Python import path.
"""

from __future__ import annotations

from pathlib import Path

from biotope.croissant.acquisition import AcquisitionContext, infer_datasets_location
from biotope.croissant.mapping import compile_mapping, load_mapping
from biotope.croissant.spec import load_from_path

# build/generated/<stem>/adapter.py -> build/ is three parents up,
# the biotope project root is four parents up.
_BUILD_DIR = Path(__file__).parent.parent.parent
_PROJECT_ROOT = _BUILD_DIR.parent
_MAPPING_FILE = _BUILD_DIR / "mappings" / "{mapping_filename}"


def build_adapter():
    """Load `{stem}`'s mapping and return a compiled BioCypher-compatible adapter."""
    mapping = load_mapping(_MAPPING_FILE)
    croissant_path = Path(mapping.croissant)
    if not croissant_path.is_absolute():
        croissant_path = (_PROJECT_ROOT / croissant_path).resolve()
    dataset = load_from_path(croissant_path)
    context = AcquisitionContext(
        dataset, datasets_location=infer_datasets_location(croissant_path)
    )
    return compile_mapping(mapping, context)
'''


_GENERATED_INIT = '''"""Generated package for `{stem}` mapping."""

from .adapter import build_adapter

__all__ = ["build_adapter"]
'''


def _emit_generated_package(stem: str, mapping_filename: str) -> tuple[str, str]:
    return (
        _GENERATED_ADAPTER_TEMPLATE.format(stem=stem, mapping_filename=mapping_filename),
        _GENERATED_INIT.format(stem=stem),
    )


# ---------------------------------------------------------------------------
# Build entry point
# ---------------------------------------------------------------------------


def _emit_build_script(project_name: str, stems: list[str], aligned: bool) -> str:
    """Build the ``create_knowledge_graph.py`` entry script."""
    imports = "\n".join(f"from generated.{stem}.adapter import build_adapter as _build_{stem}" for stem in stems)
    adapter_inits = ",\n        ".join(f'"{stem}": _build_{stem}()' for stem in stems)
    if aligned:
        alignment_import = "from biotope.croissant.alignment import load_alignment, merge_adapters\n"
        write_block = (
            "    alignment = load_alignment(HERE / 'alignment.yaml')\n"
            "    merged = merge_adapters(adapters, alignment)\n"
            "    bc.write_nodes(merged.get_nodes())\n"
            "    bc.write_edges(merged.get_edges())\n"
        )
        itertools_import = ""
    else:
        alignment_import = ""
        itertools_import = "from itertools import chain\n"
        write_block = (
            "    bc.write_nodes(chain.from_iterable(a.get_nodes() for a in adapters.values()))\n"
            "    bc.write_edges(chain.from_iterable(a.get_edges() for a in adapters.values()))\n"
        )
    return f'''"""Generated entry point for the {project_name} graph build."""

import os
from pathlib import Path
import sys
{itertools_import}
from biocypher import BioCypher

HERE = Path(__file__).parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

# Run from build/ so BioCypher's relative `output_directory: biocypher-out`
# (configured in config/biocypher_config.yaml) lands inside this build,
# where `biotope view` looks for it. Adapters resolve their own paths via
# __file__ so this chdir does not affect mapping/croissant lookup.
os.chdir(HERE)

{imports}
{alignment_import}

def build() -> None:
    bc = BioCypher(
        biocypher_config_path=str(HERE / "config" / "biocypher_config.yaml"),
        schema_config_path=str(HERE / "config" / "schema_config.yaml"),
    )

    adapters = {{
        {adapter_inits}
    }}

{write_block}    bc.write_import_call()


if __name__ == "__main__":
    build()
'''


def materialize_project(
    project_dir: Path,
    mapping_paths: list[Path],
    alignment_path: Path | None = None,
) -> dict[str, str]:
    """Write a runnable BioCypher project to ``project_dir``.

    Strict: unresolved or legacy mappings raise ``ValueError``.
    """
    project_dir.mkdir(parents=True, exist_ok=True)
    (project_dir / "config").mkdir(exist_ok=True)
    (project_dir / "mappings").mkdir(exist_ok=True)
    (project_dir / "generated").mkdir(exist_ok=True)
    (project_dir / "generated" / "__init__.py").write_text(
        '"""Generated adapters for biotope build (do not edit)."""\n'
    )

    mappings = [load_mapping(p) for p in mapping_paths]
    for mapping, path in zip(mappings, mapping_paths, strict=False):
        try:
            mapping.assert_resolved()
        except ValueError as exc:
            msg = f"Mapping {path} is not fully resolved: {exc}"
            raise ValueError(msg) from exc

    schema_config_path = project_dir / "config" / "schema_config.yaml"
    schema_config_path.write_text(_emit_schema_config(mappings))

    biocypher_config_path = project_dir / "config" / "biocypher_config.yaml"
    if not biocypher_config_path.exists():
        # `head_ontology: null` opts into BioCypher's headless mode: no remote
        # Biolink retrieval at build time. The per-build class hierarchy is
        # defined exclusively by `schema_config.yaml`, which biotope
        # regenerates deterministically from the resolved mappings on every
        # run. Schema evolution happens between builds via `project.yaml`
        # + `biotope map`, never within a build. Requires biocypher with the
        # NullOntology shim; older versions ignore the key and will still
        # fetch Biolink — upgrade if you see network errors on first run.
        biocypher_config_path.write_text(
            "biocypher:\n"
            "  dbms: csv\n"
            "  log_to_disk: true\n"
            "  output_directory: biocypher-out\n"
            "  head_ontology: null\n",
        )

    stems: list[str] = []
    for src in mapping_paths:
        stem = _mapping_stem(src)
        stems.append(stem)
        shutil.copy(src, project_dir / "mappings" / src.name)
        pkg_dir = project_dir / "generated" / stem
        pkg_dir.mkdir(exist_ok=True)
        adapter_code, init_code = _emit_generated_package(stem, src.name)
        (pkg_dir / "adapter.py").write_text(adapter_code)
        (pkg_dir / "__init__.py").write_text(init_code)

    written_alignment: Path | None = None
    if alignment_path is not None:
        load_alignment(alignment_path)  # validate
        written_alignment = project_dir / "alignment.yaml"
        shutil.copy(alignment_path, written_alignment)

    script_path = project_dir / "create_knowledge_graph.py"
    script_path.write_text(
        _emit_build_script(
            project_name=project_dir.name,
            stems=stems,
            aligned=written_alignment is not None,
        ),
    )

    return {
        "project_dir": str(project_dir),
        "schema_config": str(schema_config_path),
        "biocypher_config": str(biocypher_config_path),
        "build_script": str(script_path),
        "alignment": str(written_alignment) if written_alignment else "",
        "generated_packages": ",".join(stems),
    }


def _mapping_stem(path: Path) -> str:
    name = path.name
    for suffix in (".mapping.yaml", ".mapping.yml", ".yaml", ".yml"):
        if name.endswith(suffix):
            return name[: -len(suffix)]
    return path.stem
