"""Protect authored files when replacing derived graph reports."""

import json
from pathlib import Path
from typing import Any, cast

from biotope.graph.reports import READABLE_REPORT_VERSIONS
from biotope.graph.sources import write_text_atomic


HTML_MARKER = "<!-- Generated by biotope.graph.metagraph -->"
RUN_REPORT = "run.json"
FAILURE_REPORT = "last_failure.json"


def check_build_destination(path: Path) -> None:
    """Refuse a destination that is not a recognized build holding only its declared outputs."""
    if path.is_symlink():
        raise ValueError(f"Refusing symlink build destination {path}")
    if not path.exists():
        return
    report = path / RUN_REPORT
    if not path.is_dir() or not report.is_file():
        raise ValueError(f"Refusing to replace unrecognized build directory {path}")
    check_report_destination(report, "biotope.build")
    data = json.loads(report.read_text(encoding="utf-8"))
    declared = data.get("outputs", [])
    if not isinstance(declared, list):
        raise ValueError(f"Invalid generated output inventory in {report}")
    if any(not isinstance(item, str) for item in cast(list[object], declared)):
        raise ValueError(f"Invalid generated output inventory in {report}")
    allowed = {*cast(list[str], declared), RUN_REPORT}
    if (path / FAILURE_REPORT).exists():
        check_report_destination(path / FAILURE_REPORT, "biotope.build")
        allowed.add(FAILURE_REPORT)
    for child in path.rglob("*"):
        if child.is_symlink() or (child.is_file() and str(child.relative_to(path)) not in allowed):
            raise ValueError(f"Refusing to replace undeclared file in build directory: {child}")


def check_report_destination(path: Path, kind: str) -> None:
    """Only replace a recognized generated report, never an authored file or symlink."""
    if path.is_symlink():
        raise ValueError(f"Refusing symlink report destination {path}")
    if not path.exists():
        return
    try:
        if kind == "html":
            with path.open(encoding="utf-8") as stream:
                recognized = stream.readline().strip() == HTML_MARKER
        else:
            data = json.loads(path.read_text(encoding="utf-8"))
            recognized = (
                isinstance(data, dict)
                and cast(dict[str, Any], data).get("report_kind") == kind
                and cast(dict[str, Any], data).get("schema_version") in READABLE_REPORT_VERSIONS
            )
    except (ValueError, OSError):
        recognized = False
    if not recognized:
        raise ValueError(f"Refusing to replace authored or unrecognized generated report {path}")


def save_report(path: Path, content: str, kind: str) -> None:
    check_report_destination(path, kind)
    write_text_atomic(path, content)


def report_text(report: dict[str, Any]) -> str:
    return json.dumps(report, indent=2, sort_keys=True, allow_nan=False) + "\n"


def record_failed_build(destination: Path, report: dict[str, Any]) -> None:
    """Keep a previous build and put the failed attempt's report beside it, or start the directory with it."""
    report["outputs"] = []
    if destination.exists():
        path = destination / FAILURE_REPORT
        report["previous_build_preserved"] = True
    else:
        destination.mkdir(parents=True)
        path = destination / RUN_REPORT
    report["report_path"] = str(path)
    save_report(path, report_text(report), "biotope.build")
