"""Protect authored files when replacing derived graph reports."""

import json
from pathlib import Path
from typing import Any, cast

from biotope.graph.sources import write_text_atomic


HTML_MARKER = "<!-- Generated by biotope.graph.metagraph -->"


def check_report_destination(path: Path, kind: str) -> None:
    """Only replace a recognized generated report, never an authored file or symlink."""
    if path.is_symlink():
        raise ValueError(f"Refusing symlink report destination {path}")
    if not path.exists():
        return
    try:
        if kind == "html":
            with path.open(encoding="utf-8") as stream:
                recognized = stream.readline().strip() == HTML_MARKER
        else:
            data = json.loads(path.read_text(encoding="utf-8"))
            recognized = (
                isinstance(data, dict)
                and cast(dict[str, Any], data).get("report_kind") == kind
                and cast(dict[str, Any], data).get("schema_version") == 1
            )
    except (ValueError, OSError):
        recognized = False
    if not recognized:
        raise ValueError(f"Refusing to replace authored or unrecognized generated report {path}")


def save_report(path: Path, content: str, kind: str) -> None:
    check_report_destination(path, kind)
    write_text_atomic(path, content)
