"""Curated Croissant metadata and deterministic, declaration-only source types.

This module reads metadata, never the resources described by that metadata.
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import keyword
import logging
import os
import re
import stat
import tempfile
from collections.abc import Callable
from pathlib import Path
from typing import Any, cast


GENERATOR_VERSION = "4"
HEADER = "# Generated by biotope.graph; edit curated Croissant, then regenerate.\n"
CURATION = "biotope:curation"


class UnknownValue:
    """An unsupported source shape; refine its metadata before using its values."""


def digest(value: object) -> str:
    """Hash canonical JSON metadata or a derived definition."""
    return hashlib.sha256(
        json.dumps(value, sort_keys=True, separators=(",", ":"), allow_nan=False).encode()
    ).hexdigest()


def read_metadata(path: Path) -> dict[str, Any]:
    """Read JSON metadata while retaining extensions and original identities."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"{path}: invalid Croissant JSON: {exc}") from exc
    if not isinstance(data, dict):
        raise ValueError(f"{path}: expected a Croissant JSON object")
    data = cast(dict[str, Any], data)
    seen: set[str] = set()

    def visit(items: object, location: str) -> None:
        for i, item in enumerate(_objects(items, location)):
            pointer = location if isinstance(items, dict) else f"{location}/{i}"
            identity = item.get("@id")
            if identity is not None:
                if not isinstance(identity, str) or not identity or identity in seen:
                    raise ValueError(f"{path}:{pointer}: missing, invalid or duplicate @id {identity!r}")
                seen.add(identity)
            for key in ("field", "subField"):
                if key in item:
                    visit(item[key], f"{pointer}/{key}")

    visit(data.get("recordSet", []), "/recordSet")
    return data


def _objects(value: object, location: str) -> list[dict[str, Any]]:
    if isinstance(value, dict):
        return [cast(dict[str, Any], value)]
    if not isinstance(value, list):
        raise ValueError(f"{location}: expected an object or list of objects")
    entries = cast(list[object], value)
    if any(not isinstance(item, dict) for item in entries):
        raise ValueError(f"{location}: expected an object or list of objects")
    return cast(list[dict[str, Any]], entries)


def write_text_atomic(path: Path, text: str) -> None:
    """Replace one generated artifact without leaving a partial file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    # Normal creation honors the process umask; replacement keeps the old mode.
    # A private temporary directory hides incomplete contents without changing umask.
    mode = stat.S_IMODE(path.stat().st_mode) if path.exists() else None
    with tempfile.TemporaryDirectory(dir=path.parent, prefix=f".{path.name}.") as temporary:
        pending = Path(temporary) / "artifact"
        pending.write_text(text, encoding="utf-8")
        if mode is not None:
            pending.chmod(mode)
        os.replace(pending, path)


def _metadata_removals(previous: dict[str, Any], incoming: dict[str, Any]) -> dict[str, list[str]]:
    """Compare declaration identities and review keys, without merging metadata."""

    def identities(data: dict[str, Any]) -> tuple[set[str], set[str]]:
        records: set[str] = set()
        fields: set[str] = set()

        def visit(items: object, found: set[str]) -> None:
            for item in _objects(items, "declarations"):
                if isinstance(item.get("@id"), str):
                    found.add(item["@id"])
                for key in ("field", "subField"):
                    if key in item:
                        visit(item[key], fields)

        visit(data.get("recordSet", []), records)
        return records, fields

    old_records, old_fields = identities(previous)
    new_records, new_fields = identities(incoming)
    old_notes = previous.get(CURATION, {})
    new_notes = incoming.get(CURATION, {})
    removed = {
        "top-level keys": sorted(previous.keys() - incoming.keys()),
        "record-set IDs": sorted(old_records - new_records),
        "field IDs": sorted(old_fields - new_fields),
        "curation notes": sorted(old_notes.keys() - new_notes.keys()) if isinstance(old_notes, dict) else [],
    }
    return {label: values for label, values in removed.items() if values}


def register_metadata(
    root: Path,
    source: Path,
    name: str,
    *,
    reason: str,
    replace: bool = False,
    on_warning: Callable[[str], None] | None = None,
) -> Path:
    """Register a reviewed description; replacement requires an explicit choice.

    Args:
        root: Biotope project root.
        source: Authored Croissant JSON file.
        name: Managed dataset path, for example ``raw/study`` (without suffix).
        reason: Evidence/review note, including known omissions.
        replace: Allow replacing an existing effective description.
        on_warning: Report removed content before replacement; defaults to logging.

    Returns:
        The managed effective metadata path.
    """
    if not (root / ".biotope").is_dir():
        raise ValueError("Run biotope init first")
    relative = Path(name)
    if not name or relative.is_absolute() or ".." in relative.parts or name.endswith("/"):
        raise ValueError("Use a relative managed dataset name without '..'")
    if not reason.strip():
        raise ValueError("Supply a review reason and evidence, including unresolved gaps")
    target = root / ".biotope/datasets" / f"{name}.jsonld"
    if not target.resolve().is_relative_to((root / ".biotope/datasets").resolve()):
        raise ValueError("Managed metadata must stay under .biotope/datasets")
    if target.exists() and not replace:
        raise ValueError(f"{target} already exists; review the change and use --replace")
    data = read_metadata(source)
    notes = data.get(CURATION, {})
    if not isinstance(notes, dict):
        raise ValueError(f"{CURATION} must be an object")
    data[CURATION] = {**notes, "reason": reason}
    context = data.setdefault("@context", {})
    if isinstance(context, dict):
        cast(dict[str, Any], context).setdefault("biotope", "https://biocypher.org/biotope/")
    else:
        data["@context"] = (
            [*context, {"biotope": "https://biocypher.org/biotope/"}]
            if isinstance(context, list)
            else [context, {"biotope": "https://biocypher.org/biotope/"}]
        )
    if target.exists():
        removed = _metadata_removals(read_metadata(target), data)
        if removed:
            detail = "\n".join(
                f"  {label}: {', '.join(repr(value) for value in values)}" for label, values in removed.items()
            )
            (on_warning or logging.getLogger(__name__).warning)(f"Replacing {name!r} drops:\n{detail}")
    write_text_atomic(target, json.dumps(data, indent=2, ensure_ascii=False) + "\n")
    return target


def protect_curated(path: Path) -> None:
    """Stop a bake before it can discard registered structural corrections."""
    if path.exists() and CURATION in read_metadata(path):
        raise ValueError(
            f"{path} is curated; rebaking would replace authored corrections. "
            "Use biotope add <data-path> --bake-to review/fresh.jsonld, reconcile that description "
            "with the curated manifest, then use biotope source register --replace."
        )


def _name(raw: object, used: set[str], *, class_name: bool = False) -> str:
    base = re.sub(r"[^a-zA-Z0-9_]", "_", str(raw)).strip("_") or "unnamed"
    if class_name:
        base = "".join(part[:1].upper() + part[1:] for part in base.split("_") if part)
    if base[0].isdigit():
        base = "Record" + base if class_name else "field_" + base
    if keyword.iskeyword(base):
        base += "_"
    candidate, n = base, 2
    while candidate in used:
        candidate, n = f"{base}_{n}", n + 1
    used.add(candidate)
    return candidate


def _scalar(value: object) -> str:
    aliases = {
        "Text": "str",
        "URL": "str",
        "Date": "str",
        "DateTime": "str",
        "Boolean": "bool",
        "Integer": "int",
        "Float": "float",
        "Number": "float",
    }
    numeric = {
        "Bool": "bool",
        **{f"{kind}{n}": "int" for kind in ("Int", "UInt") for n in (8, 16, 32, 64)},
        **{f"Float{n}": "float" for n in (16, 32, 64)},
    }
    for prefix, types in (
        ("sc:", aliases),
        ("https://schema.org/", aliases),
        ("http://schema.org/", aliases),
        ("cr:", numeric),
        ("http://mlcommons.org/croissant/", numeric),
        ("https://mlcommons.org/croissant/", numeric),
    ):
        if isinstance(value, str) and value.startswith(prefix):
            return types.get(value[len(prefix) :], "UnknownValue")
    return "UnknownValue"


def source_definition(data: dict[str, Any]) -> dict[str, Any]:
    """Select the declarations and interpretation context; exclude payload bookkeeping."""
    return {"@context": data.get("@context"), "recordSet": data.get("recordSet", [])}


def render_source(data: dict[str, Any]) -> str:
    """Render dataclasses with references to authoritative Croissant fields.

    Retain only field IDs (or JSON pointers when absent) and a freshness digest.
    Descriptions, extraction rules and extensions stay in the Croissant file.
    Unknown shapes are opaque; scalars and repeated elements default to nullable.
    """
    data = source_definition(data)
    revision = digest(data)
    lines: list[str] = []
    needs_unknown = False
    classes: set[str] = {
        "UnknownValue",
        "ClassVar",
        "SOURCE_DIGEST",
        "GENERATOR_VERSION",
        "RECORDS",
        "SourceRow",
        "TypeAlias",
        "NoReturn",
        "Union",
    }

    def emit(record: dict[str, Any], pointer: str, suggested: str, *, nested: bool = False) -> str:
        nonlocal needs_unknown
        cls = _name(suggested, classes, class_name=True)
        attributes: list[str] = []
        field_refs: list[str] = []
        used = {"__record_set__", "__source_digest__", "__field_refs__"}
        child_key = "subField" if nested else "field"
        child_value = record.get(child_key, [])
        children = _objects(child_value, f"{pointer}/{child_key}")
        for index, item in enumerate(children):
            locator = f"{pointer}/{child_key}"
            if not isinstance(child_value, dict):
                locator += f"/{index}"
            attr = _name(item.get("name", item.get("@id", "unnamed")), used)
            dtype = (
                emit(item, locator, f"{cls}_{attr}", nested=True)
                if item.get("subField")
                else _scalar(item.get("dataType"))
            )
            shape = item.get("arrayShape", item.get("cr:arrayShape"))
            if shape is not None:
                dtype = "UnknownValue"
            needs_unknown |= dtype == "UnknownValue"
            if shape is None and item.get("repeated", item.get("isArray", item.get("cr:isArray", False))):
                dtype = f"list[{dtype} | None]"
            nullable = item.get("biotope:nullable", True)
            if not isinstance(nullable, bool):
                raise ValueError(f"{locator}: biotope:nullable must be true or false")
            if nullable:
                dtype += " | None"
            field_refs.append(f"        {attr!r}: {item.get('@id', locator)!r},")
            default = " = None" if nullable else ""
            attributes.append(f"    {attr}: {dtype}{default}")
        lines.extend(
            [
                "@dataclass(frozen=True, kw_only=True)",
                f"class {cls}:",
                f"    __record_set__: ClassVar[str] = {record.get('@id', pointer)!r}",
                "    __source_digest__: ClassVar[str] = SOURCE_DIGEST",
                "",
                *attributes,
                "",
                "    __field_refs__: ClassVar[dict[str, str]] = {",
                *field_refs,
                "    }",
                "",
                "",
            ]
        )
        return cls

    records = _objects(data.get("recordSet", []), "/recordSet")
    record_names = [
        emit(
            record,
            "/recordSet" if isinstance(data.get("recordSet"), dict) else f"/recordSet/{index}",
            record.get("name", record.get("@id", "record")),
        )
        for index, record in enumerate(records)
    ]
    imports: list[str] = []
    if records:
        imports += [
            "from dataclasses import dataclass",
            "from typing import ClassVar, TypeAlias" + (", Union" if len(records) > 1 else ""),
        ]
    else:
        imports += ["from typing import NoReturn, TypeAlias"]
    if needs_unknown:
        imports += ["from biotope.graph.sources import UnknownValue"]
    preamble = [
        HEADER.rstrip(),
        "from __future__ import annotations",
        "",
        *imports,
        "",
        f"GENERATOR_VERSION = {GENERATOR_VERSION!r}",
        f"SOURCE_DIGEST = {revision!r}",
    ]
    # A flat Union avoids Pyright's parse-depth limit on hundreds of chained | expressions.
    row_type = "Union[" + ", ".join(record_names) + "]" if len(records) > 1 else next(iter(record_names), "NoReturn")
    inventory = [
        "RECORDS: tuple[type, ...] = (" + " ".join(f"{name}," for name in record_names) + ")",
        "SourceRow: TypeAlias = " + row_type,
    ]
    return "\n".join([*preamble, "", *lines, *inventory]).rstrip() + "\n"


def generate_source(metadata: Path, output: Path) -> Path:
    """Generate one module, refusing to overwrite authored Python."""
    code = render_source(read_metadata(metadata))
    if output.exists() and not output.read_text(encoding="utf-8").startswith(HEADER):
        raise ValueError(f"{output} is authored code; choose a separate generated module")
    if output.resolve() == metadata.resolve():
        raise ValueError("Generated code must not overwrite metadata")
    write_text_atomic(output, code)
    Path(importlib.util.cache_from_source(str(output))).unlink(missing_ok=True)
    return output


def generate_source_package(metadata: Path, output: Path) -> tuple[Path, ...]:
    """Generate a contract and create missing, project-owned registration/loader files."""
    if (
        output.suffix != ".py"
        or not output.stem.isidentifier()
        or keyword.iskeyword(output.stem)
        or output.stem in {"__init__", "loader"}
    ):
        raise ValueError(
            "Use an importable generated module name, e.g. graph/sources/study/schema.py; "
            "keep __init__.py and loader.py authored"
        )
    relative_metadata = Path(os.path.relpath(metadata.resolve(), output.parent.resolve())).as_posix()
    registration = f'''"""Project-owned source registration; generated record inventory stays current."""

from pathlib import Path

from biotope.graph import SourceContract

from .{output.stem} import RECORDS


SOURCE = SourceContract(
    name={output.parent.name!r},
    metadata=Path(__file__).resolve().parent / {relative_metadata!r},
    generated=Path(__file__).with_name({output.name!r}),
    records=RECORDS,
)
'''
    template = Path(__file__).resolve().parents[1] / "templates/graph/sources/_example/loader.py"
    loader = template.read_text(encoding="utf-8").replace("from .schema import", f"from .{output.stem} import")
    generated = generate_source(metadata, output)
    created = [generated]
    for name, contents in (("__init__.py", registration), ("loader.py", loader)):
        target = output.with_name(name)
        if target.exists() or target.is_symlink():
            continue
        # Exclusive creation also preserves a file authored during generation.
        try:
            with target.open("x", encoding="utf-8") as stream:
                stream.write(contents)
        except FileExistsError:
            continue
        created.append(target)
    return tuple(created)


def check_generated(metadata: Path, output: Path) -> None:
    """Reject a changed manifest or modified/stale generated module."""
    if not output.is_file() or output.read_text(encoding="utf-8") != render_source(read_metadata(metadata)):
        raise ValueError(
            f"{output} is stale; run biotope source generate {metadata} --out {output}, then review mappings"
        )
