"""Curated Croissant metadata: reading, registration, naming and binding authored schemas.

This module reads metadata, never the resources described by that metadata.
"""

from __future__ import annotations

import hashlib
import json
import keyword
import logging
import os
import re
import stat
import tempfile
from collections import Counter
from collections.abc import Callable, Iterator
from dataclasses import dataclass, fields, is_dataclass
from pathlib import Path
from typing import Any, Literal, cast, get_type_hints

from biotope.graph.annotations import is_string, nested_records
from biotope.graph.standardization import field_aliases, field_bindings


# The 0.9 generator's header: schemas carrying it are authored files now, and a root carrying it is regenerated.
LEGACY_HEADER = "# Generated by biotope.graph; edit curated Croissant, then regenerate.\n"
GENERATED_HEADER = "# Generated by biotope; do not edit. Regenerate with biotope source generate.\n"
CURATION = "biotope:curation"
RECORD_SET_MARKER = "# biotope:record-set "
MANIFEST_MARKER = "# biotope:manifest "
PLACEHOLDER_MARKER = "# biotope:placeholder"

Kind = Literal["recordSet", "fileObject", "fileSet"]
FILE_KINDS: tuple[Kind, ...] = ("fileObject", "fileSet")


def _croissant_types(name: str) -> frozenset[str]:
    return frozenset(
        {f"cr:{name}", f"http://mlcommons.org/croissant/{name}", f"https://mlcommons.org/croissant/{name}"}
    )


@dataclass(frozen=True)
class KindSpec:
    """How one kind of source is named to users, declared in a schema and typed in a manifest."""

    label: str
    attribute: str
    types: frozenset[str] = frozenset()


# File kinds come first because a document-facts class also declares ``__record_set__``.
KINDS: dict[Kind, KindSpec] = {
    "fileObject": KindSpec("FileObject", "__file_object__", _croissant_types("FileObject")),
    "fileSet": KindSpec("FileSet", "__file_set__", _croissant_types("FileSet")),
    "recordSet": KindSpec("record set", "__record_set__"),
}

# The names 0.9 package naming avoided, frozen so that no existing package is ever renamed.
RESERVED_NAMES = frozenset(
    {
        "__init__",
        "__pycache__",
        "loader",
        "schema",
        "RECORDS",
        "SourceRow",
        "SOURCE_DIGEST",
        "GENERATOR_VERSION",
        "UnknownValue",
        "ClassVar",
        "TypeAlias",
        "dataclass",
        "annotations",
        "SourceContract",
        "CONTRACTS",
    }
)
# Long enough for real record-set ids, short enough for eCryptfs' 143-byte names.
SLUG_LIMIT = 80


class StaleBinding(ValueError):
    """A schema's acknowledged revision differs from its manifest's current revision."""

    def __init__(self, message: str, expected: str) -> None:
        super().__init__(message)
        self.expected = expected


class UnknownValue:
    """An unsupported source shape; refine its metadata before using its values."""


def digest(value: object) -> str:
    """Hash canonical JSON metadata or a derived definition."""
    return hashlib.sha256(
        json.dumps(value, sort_keys=True, separators=(",", ":"), allow_nan=False).encode()
    ).hexdigest()


def read_metadata(path: Path) -> dict[str, Any]:
    """Read JSON metadata while retaining extensions and original identities."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"{path}: invalid Croissant JSON: {exc}") from exc
    if not isinstance(data, dict):
        raise ValueError(f"{path}: expected a Croissant JSON object")
    data = cast(dict[str, Any], data)
    seen: set[str] = set()

    def visit(items: object, location: str) -> None:
        for i, item in enumerate(objects(items, location)):
            pointer = location if isinstance(items, dict) else f"{location}/{i}"
            identity = item.get("@id")
            if identity is not None:
                if not isinstance(identity, str) or not identity or identity in seen:
                    raise ValueError(f"{path}:{pointer}: missing, invalid or duplicate @id {identity!r}")
                seen.add(identity)
            if not isinstance(item.get("biotope:nullable", True), bool):
                raise ValueError(f"{path}:{pointer}: biotope:nullable must be true or false")
            for key in ("field", "subField"):
                if key in item:
                    visit(item[key], f"{pointer}/{key}")

    visit(data.get("recordSet", []), "/recordSet")
    return data


def objects(value: object, location: str) -> list[dict[str, Any]]:
    if isinstance(value, dict):
        return [cast(dict[str, Any], value)]
    if not isinstance(value, list):
        raise ValueError(f"{location}: expected an object or list of objects")
    entries = cast(list[object], value)
    if any(not isinstance(item, dict) for item in entries):
        raise ValueError(f"{location}: expected an object or list of objects")
    return cast(list[dict[str, Any]], entries)


@dataclass(frozen=True)
class FieldNode:
    """One described field, identified by its ``@id`` or, without one, by its position under its parent."""

    item: dict[str, Any]
    locator: str
    identity: str
    scope: str

    @property
    def scoped(self) -> bool:
        """Whether the identity sits under its parent's, which ``source_field`` bindings rely on."""
        return self.identity.startswith(self.scope + "/")

    @property
    def nullable(self) -> bool:
        return self.item.get("biotope:nullable", True)

    def children(self) -> list[FieldNode]:
        return child_fields(self.item, self.locator, self.identity, nested=True) if self.item.get("subField") else []


def child_fields(record: dict[str, Any], pointer: str, scope: str, *, nested: bool = False) -> list[FieldNode]:
    """The fields of a record set, or the subfields of a field."""
    key = "subField" if nested else "field"
    value = record.get(key, [])
    location = f"{pointer}/{key}"
    nodes: list[FieldNode] = []
    for index, item in enumerate(objects(value, location)):
        locator = location if isinstance(value, dict) else f"{location}/{index}"
        nodes.append(FieldNode(item, locator, str(item.get("@id", locator)), scope))
    return nodes


def walk_fields(record: dict[str, Any], identity: str) -> Iterator[FieldNode]:
    """Every field of one record set, each subfield right after its parent."""
    pending = child_fields(record, identity, identity)[::-1]
    while pending:
        node = pending.pop()
        yield node
        pending.extend(node.children()[::-1])


def write_text_atomic(path: Path, text: str) -> None:
    """Replace one generated artifact without leaving a partial file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    # Normal creation honors the process umask; replacement keeps the old mode.
    # A private temporary directory hides incomplete contents without changing umask.
    mode = stat.S_IMODE(path.stat().st_mode) if path.exists() else None
    with tempfile.TemporaryDirectory(dir=path.parent, prefix=f".{path.name}.") as temporary:
        pending = Path(temporary) / "artifact"
        pending.write_text(text, encoding="utf-8")
        if mode is not None:
            pending.chmod(mode)
        os.replace(pending, path)


def _metadata_removals(previous: dict[str, Any], incoming: dict[str, Any]) -> dict[str, list[str]]:
    """Compare declaration identities and review keys, without merging metadata."""

    def identities(data: dict[str, Any]) -> tuple[set[str], set[str]]:
        records: set[str] = set()
        fields: set[str] = set()

        def visit(items: object, found: set[str]) -> None:
            for item in objects(items, "declarations"):
                if isinstance(item.get("@id"), str):
                    found.add(item["@id"])
                for key in ("field", "subField"):
                    if key in item:
                        visit(item[key], fields)

        visit(data.get("recordSet", []), records)
        return records, fields

    old_records, old_fields = identities(previous)
    new_records, new_fields = identities(incoming)
    old_notes = previous.get(CURATION, {})
    new_notes = incoming.get(CURATION, {})
    removed = {
        "top-level keys": sorted(previous.keys() - incoming.keys()),
        "record-set IDs": sorted(old_records - new_records),
        "field IDs": sorted(old_fields - new_fields),
        "curation notes": sorted(old_notes.keys() - new_notes.keys()) if isinstance(old_notes, dict) else [],
    }
    return {label: values for label, values in removed.items() if values}


def register_metadata(
    root: Path,
    source: Path,
    name: str,
    *,
    reason: str,
    replace: bool = False,
    on_warning: Callable[[str], None] | None = None,
) -> Path:
    """Register a reviewed description; replacement requires an explicit choice.

    Args:
        root: Biotope project root.
        source: Authored Croissant JSON file.
        name: Managed dataset path, for example ``raw/study`` (without suffix).
        reason: Evidence/review note, including known omissions.
        replace: Allow replacing an existing effective description.
        on_warning: Report removed content before replacement; defaults to logging.

    Returns:
        The managed effective metadata path.
    """
    if not (root / ".biotope").is_dir():
        raise ValueError("Run biotope init first")
    relative = Path(name)
    if not name or relative.is_absolute() or ".." in relative.parts or name.endswith("/"):
        raise ValueError("Use a relative managed dataset name without '..'")
    if not reason.strip():
        raise ValueError("Supply a review reason and evidence, including unresolved gaps")
    target = root / ".biotope/datasets" / f"{name}.jsonld"
    if not target.resolve().is_relative_to((root / ".biotope/datasets").resolve()):
        raise ValueError("Managed metadata must stay under .biotope/datasets")
    if target.exists() and not replace:
        raise ValueError(f"{target} already exists; review the change and use --replace")
    data = read_metadata(source)
    notes = data.get(CURATION, {})
    if not isinstance(notes, dict):
        raise ValueError(f"{CURATION} must be an object")
    data[CURATION] = {**notes, "reason": reason}
    context = data.setdefault("@context", {})
    if isinstance(context, dict):
        cast(dict[str, Any], context).setdefault("biotope", "https://biocypher.org/biotope/")
    else:
        data["@context"] = (
            [*context, {"biotope": "https://biocypher.org/biotope/"}]
            if isinstance(context, list)
            else [context, {"biotope": "https://biocypher.org/biotope/"}]
        )
    if target.exists():
        removed = _metadata_removals(read_metadata(target), data)
        if removed:
            detail = "\n".join(
                f"  {label}: {', '.join(repr(value) for value in values)}" for label, values in removed.items()
            )
            (on_warning or logging.getLogger(__name__).warning)(f"Replacing {name!r} drops:\n{detail}")
    write_text_atomic(target, json.dumps(data, indent=2, ensure_ascii=False) + "\n")
    return target


def protect_curated(path: Path) -> None:
    """Stop a bake before it can discard registered structural corrections."""
    if path.exists() and CURATION in read_metadata(path):
        raise ValueError(
            f"{path} is curated; rebaking would replace authored corrections. "
            "Use biotope add <data-path> --bake-to review/fresh.jsonld, reconcile that description "
            "with the curated manifest, then use biotope source register --replace."
        )


def attribute_name(raw: object, used: set[str], *, class_name: bool = False) -> str:
    base = re.sub(r"[^a-zA-Z0-9_]", "_", str(raw)).strip("_") or "unnamed"
    if class_name:
        base = "".join(part[:1].upper() + part[1:] for part in base.split("_") if part)
    elif base[0].isdigit():
        base = "field_" + base
    if keyword.iskeyword(base):
        base += "_"
    candidate, n = base, 2
    while candidate in used:
        candidate, n = f"{base}_{n}", n + 1
    used.add(candidate)
    return candidate


def slug(raw: str) -> str:
    """Project any Croissant identity onto one importable path component."""
    base = re.sub(r"_+", "_", re.sub(r"[^A-Za-z0-9_]", "_", raw)).strip("_") or "unnamed"
    if len(base) > SLUG_LIMIT:
        base = base[:SLUG_LIMIT].rstrip("_") or "unnamed"
    if base[0].isdigit():
        base = "_" + base
    return base + "_" if keyword.iskeyword(base) else base


def python_class_name(package: str) -> str:
    # A digit-leading slug cannot capitalize into readable words, so keep it verbatim.
    base = (
        "Record" + package
        if package.startswith("_")
        else "".join(p[:1].upper() + p[1:] for p in package.split("_") if p)
    )
    return base + "_" if keyword.iskeyword(base) else base


@dataclass(frozen=True)
class RecordSetTarget:
    """One top-level record set projected onto one importable package."""

    identity: str
    package: str
    class_name: str
    record: dict[str, Any]


def record_set_targets(data: dict[str, Any]) -> tuple[RecordSetTarget, ...]:
    """Project every top-level record set onto a deterministic package and class name.

    Collisions resolve against the whole manifest and suffix every member, so
    reordering or inserting a record set never renames an unrelated package.
    """
    records = objects(data.get("recordSet", []), "/recordSet")
    single = isinstance(data.get("recordSet"), dict)
    entries: list[tuple[str, str, dict[str, Any]]] = []
    for index, record in enumerate(records):
        pointer = "/recordSet" if single else f"/recordSet/{index}"
        identity = record.get("@id") or pointer
        # Identity stays @id; naming may fall back to name for hand-authored metadata.
        preferred = record.get("@id") or record.get("name") or pointer
        entries.append((str(identity), slug(str(preferred)), record))
    counts = Counter(base for _, base, _ in entries)
    reserved = [
        counts[base] > 1 or base in RESERVED_NAMES or python_class_name(base) in RESERVED_NAMES
        for _, base, _ in entries
    ]

    def named(width: int) -> list[str]:
        return [
            f"{base}_{digest(identity)[:width]}" if taken else base
            for (identity, base, _), taken in zip(entries, reserved)
        ]

    width = 8
    packages = named(width)
    # Each name depends only on its own identity and the full slug multiset, so
    # widening stays order-independent. Distinct identities cannot share a digest.
    while len(set(packages)) != len(packages) and width < len(digest("")):
        width += 8
        packages = named(width)
    targets = [
        RecordSetTarget(identity, package, python_class_name(package), record)
        for (identity, _, record), package in zip(entries, packages)
    ]
    return tuple(targets)


def marker(text: str, prefix: str, key: str) -> str | None:
    """Read one generated header marker without importing or parsing the module."""
    for line in text.splitlines()[:4]:
        if line.startswith(prefix):
            try:
                value = cast(object, json.loads(line[len(prefix) :]))
            except json.JSONDecodeError:
                return None
            found = cast(dict[str, object], value).get(key) if isinstance(value, dict) else None
            return found if isinstance(found, str) else None
    return None


def scalar_type(value: object) -> str:
    aliases = {
        "Text": "str",
        "URL": "str",
        "Date": "str",
        "DateTime": "str",
        "Boolean": "bool",
        "Integer": "int",
        "Float": "float",
        "Number": "float",
    }
    numeric = {
        "Bool": "bool",
        **{f"{kind}{n}": "int" for kind in ("Int", "UInt") for n in (8, 16, 32, 64)},
        **{f"Float{n}": "float" for n in (16, 32, 64)},
    }
    for prefix, types in (
        ("sc:", aliases),
        ("https://schema.org/", aliases),
        ("http://schema.org/", aliases),
        ("cr:", numeric),
        ("http://mlcommons.org/croissant/", numeric),
        ("https://mlcommons.org/croissant/", numeric),
    ):
        if isinstance(value, str) and value.startswith(prefix):
            return types.get(value[len(prefix) :], "UnknownValue")
    return "UnknownValue"


def record_set_definition(data: dict[str, Any], target: RecordSetTarget) -> dict[str, Any]:
    """Narrow the declarations to one record set, so unrelated edits leave it unchanged."""
    return {"@context": data.get("@context"), "recordSet": [target.record]}


def file_definition(data: dict[str, Any], resource: dict[str, Any]) -> dict[str, Any]:
    """Narrow the declarations to one FileObject or FileSet, including its checksum."""
    return {"@context": data.get("@context"), "distribution": resource}


def resource_kinds(resource: dict[str, Any]) -> set[str]:
    """Return a distribution entry's declared types as a set."""
    kinds: object = resource.get("@type", [])
    if isinstance(kinds, str):
        return {kinds}
    return {kind for kind in cast(list[object], kinds) if isinstance(kind, str)} if isinstance(kinds, list) else set()


def resource_kind(resource: dict[str, Any]) -> Kind | None:
    """Whether a distribution entry is a FileObject or a FileSet; a FileObject when it claims both."""
    declared = resource_kinds(resource)
    return next((kind for kind in FILE_KINDS if declared & KINDS[kind].types), None)


def _check_fields(record: type, nodes: list[FieldNode], scope: str = "") -> None:
    """Keep all described fields bound while allowing authored names and value types."""
    expected = {node.identity: node for node in nodes}
    untyped = cast(dict[object, object], field_bindings(record, scope))
    if any(not isinstance(name, str) or not isinstance(reference, str) for name, reference in untyped.items()):
        raise ValueError(f"{record.__name__}: source field bindings must contain string names and identities")
    bindings = cast(dict[str, str], untyped)
    attributes = {member.name for member in fields(record)}
    unknown_attributes = set(bindings) - attributes
    missing = set(expected) - set(bindings.values())
    unknown_references = set(bindings.values()) - set(expected)
    duplicates = [ref for ref, count in Counter(bindings.values()).items() if count > 1]
    if unknown_attributes or missing or unknown_references or duplicates:
        raise ValueError(
            f"{record.__name__}: invalid source field coverage; "
            f"unbound source fields={sorted(missing)}, "
            f"unknown source fields={sorted(unknown_references)}, "
            f"unknown attributes={sorted(unknown_attributes)}, duplicate bindings={sorted(duplicates)}"
        )
    annotations = get_type_hints(record)
    for name, aliases in cast(dict[object, object], field_aliases(record)).items():
        if not isinstance(name, str) or name not in bindings:
            raise ValueError(f"{record.__name__}: value aliases refer to an unbound source attribute {name!r}")
        if not isinstance(aliases, dict) or not aliases:
            raise ValueError(f"{record.__name__}.{name}: value aliases must be a nonempty string-to-string dictionary")
        if not is_string(annotations[name]):
            raise ValueError(f"{record.__name__}.{name}: string value aliases require a string-valued schema field")
        for token, value in cast(dict[object, object], aliases).items():
            if not isinstance(token, str) or not token or token != token.strip().lower() or not isinstance(value, str):
                raise ValueError(
                    f"{record.__name__}.{name}: value aliases require trimmed lowercase tokens and string outputs"
                )
    for name, reference in bindings.items():
        if children := expected[reference].children():
            for nested in nested_records(annotations[name]):
                _check_fields(nested, children, reference)


def check_source_record(data: dict[str, Any], record: object) -> str:
    """Check a RecordSet, FileObject or FileSet binding and return the manifest's current revision.

    An authored schema may standardize names and types, but a table schema must bind every described
    field. Document facts bind to their file without fabricating a raw RecordSet.
    """
    if not isinstance(record, type) or not is_dataclass(record):
        raise ValueError(f"{record!r}: source records must be dataclass types")
    if not getattr(record, "__dataclass_params__").frozen:
        raise ValueError(f"{record.__name__}: source records must be frozen dataclasses")
    identity = getattr(record, "__record_set__", None)
    if not isinstance(identity, str) or not identity.strip():
        raise ValueError(f"{record.__name__}: declare a nonempty __record_set__ evidence identity")
    file_object = getattr(record, "__file_object__", None)
    file_set = getattr(record, "__file_set__", None)
    if file_object is not None and file_set is not None:
        raise ValueError(f"{record.__name__}: declare either __file_object__ or __file_set__, not both")
    file_identity = file_object if file_object is not None else file_set
    if file_identity is not None:
        spec = KINDS["fileObject" if file_object is not None else "fileSet"]
        if not isinstance(file_identity, str) or not file_identity.strip():
            raise ValueError(f"{record.__name__}: invalid {spec.label} identity")
        files = [
            item for item in objects(data.get("distribution", []), "/distribution") if item.get("@id") == file_identity
        ]
        if len(files) != 1:
            raise ValueError(f"{record.__name__}: {spec.label} {file_identity!r} is missing or ambiguous")
        file = files[0]
        if not resource_kinds(file) & spec.types:
            raise ValueError(f"{record.__name__}: {file_identity!r} is not a {spec.label}")
        if not identity.startswith(file_identity + "/") or identity == file_identity + "/":
            raise ValueError(f"{record.__name__}: document record identity must be scoped under {file_identity!r}")
        expected = digest(file_definition(data, file))
    else:
        target = next((target for target in record_set_targets(data) if target.identity == identity), None)
        if target is None:
            raise ValueError(f"{record.__name__}: RecordSet {identity!r} is missing from metadata")
        expected = digest(record_set_definition(data, target))
        _check_fields(record, child_fields(target.record, target.identity, target.identity))
    if getattr(record, "__source_digest__", None) != expected:
        raise StaleBinding(
            f"{record.__name__}: stale source binding; review the changed metadata and update the schema", expected
        )
    return expected
