"""Curated Croissant metadata and deterministic, declaration-only source types.

This module reads metadata, never the resources described by that metadata.
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import keyword
import logging
import os
import re
import stat
import tempfile
from collections import Counter
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any, cast


GENERATOR_VERSION = "5"
HEADER = "# Generated by biotope.graph; edit curated Croissant, then regenerate.\n"
CURATION = "biotope:curation"
# Machine-readable identity on line two, read textually so a stale module still parses.
RECORD_SET_MARKER = "# biotope:record-set "
MANIFEST_MARKER = "# biotope:manifest "
RESERVED_NAMES = frozenset(
    {
        # Generated module filenames and package machinery.
        "__init__",
        "__pycache__",
        "loader",
        "schema",
        # Module-level names in a generated schema.py.
        "RECORDS",
        "SourceRow",
        "SOURCE_DIGEST",
        "GENERATOR_VERSION",
        "UnknownValue",
        "ClassVar",
        "TypeAlias",
        "dataclass",
        "annotations",
        # Module-level names in a generated inventory __init__.py.
        "SourceContract",
        "CONTRACTS",
    }
)
# Long enough for real record-set ids, short enough for eCryptfs' 143-byte names.
SLUG_LIMIT = 80


class UnknownValue:
    """An unsupported source shape; refine its metadata before using its values."""


def digest(value: object) -> str:
    """Hash canonical JSON metadata or a derived definition."""
    return hashlib.sha256(
        json.dumps(value, sort_keys=True, separators=(",", ":"), allow_nan=False).encode()
    ).hexdigest()


def read_metadata(path: Path) -> dict[str, Any]:
    """Read JSON metadata while retaining extensions and original identities."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"{path}: invalid Croissant JSON: {exc}") from exc
    if not isinstance(data, dict):
        raise ValueError(f"{path}: expected a Croissant JSON object")
    data = cast(dict[str, Any], data)
    seen: set[str] = set()

    def visit(items: object, location: str) -> None:
        for i, item in enumerate(_objects(items, location)):
            pointer = location if isinstance(items, dict) else f"{location}/{i}"
            identity = item.get("@id")
            if identity is not None:
                if not isinstance(identity, str) or not identity or identity in seen:
                    raise ValueError(f"{path}:{pointer}: missing, invalid or duplicate @id {identity!r}")
                seen.add(identity)
            for key in ("field", "subField"):
                if key in item:
                    visit(item[key], f"{pointer}/{key}")

    visit(data.get("recordSet", []), "/recordSet")
    return data


def _objects(value: object, location: str) -> list[dict[str, Any]]:
    if isinstance(value, dict):
        return [cast(dict[str, Any], value)]
    if not isinstance(value, list):
        raise ValueError(f"{location}: expected an object or list of objects")
    entries = cast(list[object], value)
    if any(not isinstance(item, dict) for item in entries):
        raise ValueError(f"{location}: expected an object or list of objects")
    return cast(list[dict[str, Any]], entries)


def write_text_atomic(path: Path, text: str) -> None:
    """Replace one generated artifact without leaving a partial file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    # Normal creation honors the process umask; replacement keeps the old mode.
    # A private temporary directory hides incomplete contents without changing umask.
    mode = stat.S_IMODE(path.stat().st_mode) if path.exists() else None
    with tempfile.TemporaryDirectory(dir=path.parent, prefix=f".{path.name}.") as temporary:
        pending = Path(temporary) / "artifact"
        pending.write_text(text, encoding="utf-8")
        if mode is not None:
            pending.chmod(mode)
        os.replace(pending, path)


def _metadata_removals(previous: dict[str, Any], incoming: dict[str, Any]) -> dict[str, list[str]]:
    """Compare declaration identities and review keys, without merging metadata."""

    def identities(data: dict[str, Any]) -> tuple[set[str], set[str]]:
        records: set[str] = set()
        fields: set[str] = set()

        def visit(items: object, found: set[str]) -> None:
            for item in _objects(items, "declarations"):
                if isinstance(item.get("@id"), str):
                    found.add(item["@id"])
                for key in ("field", "subField"):
                    if key in item:
                        visit(item[key], fields)

        visit(data.get("recordSet", []), records)
        return records, fields

    old_records, old_fields = identities(previous)
    new_records, new_fields = identities(incoming)
    old_notes = previous.get(CURATION, {})
    new_notes = incoming.get(CURATION, {})
    removed = {
        "top-level keys": sorted(previous.keys() - incoming.keys()),
        "record-set IDs": sorted(old_records - new_records),
        "field IDs": sorted(old_fields - new_fields),
        "curation notes": sorted(old_notes.keys() - new_notes.keys()) if isinstance(old_notes, dict) else [],
    }
    return {label: values for label, values in removed.items() if values}


def register_metadata(
    root: Path,
    source: Path,
    name: str,
    *,
    reason: str,
    replace: bool = False,
    on_warning: Callable[[str], None] | None = None,
) -> Path:
    """Register a reviewed description; replacement requires an explicit choice.

    Args:
        root: Biotope project root.
        source: Authored Croissant JSON file.
        name: Managed dataset path, for example ``raw/study`` (without suffix).
        reason: Evidence/review note, including known omissions.
        replace: Allow replacing an existing effective description.
        on_warning: Report removed content before replacement; defaults to logging.

    Returns:
        The managed effective metadata path.
    """
    if not (root / ".biotope").is_dir():
        raise ValueError("Run biotope init first")
    relative = Path(name)
    if not name or relative.is_absolute() or ".." in relative.parts or name.endswith("/"):
        raise ValueError("Use a relative managed dataset name without '..'")
    if not reason.strip():
        raise ValueError("Supply a review reason and evidence, including unresolved gaps")
    target = root / ".biotope/datasets" / f"{name}.jsonld"
    if not target.resolve().is_relative_to((root / ".biotope/datasets").resolve()):
        raise ValueError("Managed metadata must stay under .biotope/datasets")
    if target.exists() and not replace:
        raise ValueError(f"{target} already exists; review the change and use --replace")
    data = read_metadata(source)
    notes = data.get(CURATION, {})
    if not isinstance(notes, dict):
        raise ValueError(f"{CURATION} must be an object")
    data[CURATION] = {**notes, "reason": reason}
    context = data.setdefault("@context", {})
    if isinstance(context, dict):
        cast(dict[str, Any], context).setdefault("biotope", "https://biocypher.org/biotope/")
    else:
        data["@context"] = (
            [*context, {"biotope": "https://biocypher.org/biotope/"}]
            if isinstance(context, list)
            else [context, {"biotope": "https://biocypher.org/biotope/"}]
        )
    if target.exists():
        removed = _metadata_removals(read_metadata(target), data)
        if removed:
            detail = "\n".join(
                f"  {label}: {', '.join(repr(value) for value in values)}" for label, values in removed.items()
            )
            (on_warning or logging.getLogger(__name__).warning)(f"Replacing {name!r} drops:\n{detail}")
    write_text_atomic(target, json.dumps(data, indent=2, ensure_ascii=False) + "\n")
    return target


def protect_curated(path: Path) -> None:
    """Stop a bake before it can discard registered structural corrections."""
    if path.exists() and CURATION in read_metadata(path):
        raise ValueError(
            f"{path} is curated; rebaking would replace authored corrections. "
            "Use biotope add <data-path> --bake-to review/fresh.jsonld, reconcile that description "
            "with the curated manifest, then use biotope source register --replace."
        )


def _name(raw: object, used: set[str], *, class_name: bool = False) -> str:
    base = re.sub(r"[^a-zA-Z0-9_]", "_", str(raw)).strip("_") or "unnamed"
    if class_name:
        base = "".join(part[:1].upper() + part[1:] for part in base.split("_") if part)
    elif base[0].isdigit():
        base = "field_" + base
    if keyword.iskeyword(base):
        base += "_"
    candidate, n = base, 2
    while candidate in used:
        candidate, n = f"{base}_{n}", n + 1
    used.add(candidate)
    return candidate


def _slug(raw: str) -> str:
    """Project any Croissant identity onto one importable path component."""
    base = re.sub(r"_+", "_", re.sub(r"[^A-Za-z0-9_]", "_", raw)).strip("_") or "unnamed"
    if len(base) > SLUG_LIMIT:
        base = base[:SLUG_LIMIT].rstrip("_") or "unnamed"
    if base[0].isdigit():
        base = "_" + base
    return base + "_" if keyword.iskeyword(base) else base


def _class_name(package: str) -> str:
    # A digit-leading slug cannot capitalize into readable words, so keep it verbatim.
    base = (
        "Record" + package
        if package.startswith("_")
        else "".join(p[:1].upper() + p[1:] for p in package.split("_") if p)
    )
    return base + "_" if keyword.iskeyword(base) else base


@dataclass(frozen=True)
class RecordSetTarget:
    """One top-level record set projected onto one importable package."""

    identity: str
    package: str
    class_name: str
    record: dict[str, Any]


def record_set_targets(data: dict[str, Any]) -> tuple[RecordSetTarget, ...]:
    """Project every top-level record set onto a deterministic package and class name.

    Collisions resolve against the whole manifest and suffix every member, so
    reordering or inserting a record set never renames an unrelated package.
    """
    records = _objects(data.get("recordSet", []), "/recordSet")
    single = isinstance(data.get("recordSet"), dict)
    entries: list[tuple[str, str, dict[str, Any]]] = []
    for index, record in enumerate(records):
        pointer = "/recordSet" if single else f"/recordSet/{index}"
        identity = record.get("@id") or pointer
        # Identity stays @id; naming may fall back to name for hand-authored metadata.
        preferred = record.get("@id") or record.get("name") or pointer
        entries.append((str(identity), _slug(str(preferred)), record))
    counts = Counter(slug for _, slug, _ in entries)
    reserved = [
        counts[slug] > 1 or slug in RESERVED_NAMES or _class_name(slug) in RESERVED_NAMES for _, slug, _ in entries
    ]

    def named(width: int) -> list[str]:
        return [
            f"{slug}_{digest(identity)[:width]}" if taken else slug
            for (identity, slug, _), taken in zip(entries, reserved)
        ]

    width = 8
    packages = named(width)
    # Each name depends only on its own identity and the full slug multiset, so
    # widening stays order-independent. Distinct identities cannot share a digest.
    while len(set(packages)) != len(packages) and width < len(digest("")):
        width += 8
        packages = named(width)
    targets = [
        RecordSetTarget(identity, package, _class_name(package), record)
        for (identity, _, record), package in zip(entries, packages)
    ]
    return tuple(targets)


def _marker(text: str, prefix: str, key: str) -> str | None:
    """Read one generated header marker without importing or parsing the module."""
    for line in text.splitlines()[:4]:
        if line.startswith(prefix):
            try:
                marker = cast(object, json.loads(line[len(prefix) :]))
            except json.JSONDecodeError:
                return None
            value = cast(dict[str, object], marker).get(key) if isinstance(marker, dict) else None
            return value if isinstance(value, str) else None
    return None


def header_identity(text: str) -> str | None:
    """Read a generated module's own record-set identity."""
    return _marker(text, RECORD_SET_MARKER, "id")


def _positional(found: str | None, identity: str) -> bool:
    """Report whether both identities are manifest positions rather than stable IDs."""
    return bool(found) and found.startswith("/recordSet") and identity.startswith("/recordSet")


def _scalar(value: object) -> str:
    aliases = {
        "Text": "str",
        "URL": "str",
        "Date": "str",
        "DateTime": "str",
        "Boolean": "bool",
        "Integer": "int",
        "Float": "float",
        "Number": "float",
    }
    numeric = {
        "Bool": "bool",
        **{f"{kind}{n}": "int" for kind in ("Int", "UInt") for n in (8, 16, 32, 64)},
        **{f"Float{n}": "float" for n in (16, 32, 64)},
    }
    for prefix, types in (
        ("sc:", aliases),
        ("https://schema.org/", aliases),
        ("http://schema.org/", aliases),
        ("cr:", numeric),
        ("http://mlcommons.org/croissant/", numeric),
        ("https://mlcommons.org/croissant/", numeric),
    ):
        if isinstance(value, str) and value.startswith(prefix):
            return types.get(value[len(prefix) :], "UnknownValue")
    return "UnknownValue"


def record_set_definition(data: dict[str, Any], target: RecordSetTarget) -> dict[str, Any]:
    """Narrow the declarations to one record set, so unrelated edits leave it unchanged."""
    return {"@context": data.get("@context"), "recordSet": [target.record]}


def contract_digests(data: dict[str, Any]) -> dict[str, str]:
    """Map every record-set identity to the freshness digest generation embeds."""
    return {t.identity: digest(record_set_definition(data, t)) for t in record_set_targets(data)}


def render_source(data: dict[str, Any], target: RecordSetTarget) -> str:
    """Render one record set's dataclasses with references to authoritative Croissant fields.

    Retain only field IDs (or a reference under the record set's identity when
    absent) and a freshness digest.
    Descriptions, extraction rules and extensions stay in the Croissant file.
    Unknown shapes are opaque; scalars and repeated elements default to nullable.
    """
    revision = digest(record_set_definition(data, target))
    lines: list[str] = []
    needs_unknown = False
    classes: set[str] = {
        "UnknownValue",
        "ClassVar",
        "SOURCE_DIGEST",
        "GENERATOR_VERSION",
        "RECORDS",
        "SourceRow",
        "TypeAlias",
    }

    def emit(record: dict[str, Any], pointer: str, cls: str, *, nested: bool = False) -> str:
        nonlocal needs_unknown
        classes.add(cls)
        attributes: list[str] = []
        field_refs: list[str] = []
        used = {"__record_set__", "__source_digest__", "__field_refs__"}
        child_key = "subField" if nested else "field"
        child_value = record.get(child_key, [])
        children = _objects(child_value, f"{pointer}/{child_key}")
        for index, item in enumerate(children):
            locator = f"{pointer}/{child_key}"
            if not isinstance(child_value, dict):
                locator += f"/{index}"
            attr = _name(item.get("name", item.get("@id", "unnamed")), used)
            dtype = (
                emit(item, locator, _name(f"{cls}_{attr}", classes, class_name=True), nested=True)
                if item.get("subField")
                else _scalar(item.get("dataType"))
            )
            shape = item.get("arrayShape", item.get("cr:arrayShape"))
            if shape is not None:
                dtype = "UnknownValue"
            needs_unknown |= dtype == "UnknownValue"
            if shape is None and item.get("repeated", item.get("isArray", item.get("cr:isArray", False))):
                dtype = f"list[{dtype} | None]"
            nullable = item.get("biotope:nullable", True)
            if not isinstance(nullable, bool):
                raise ValueError(f"{locator}: biotope:nullable must be true or false")
            if nullable:
                dtype += " | None"
            field_refs.append(f"        {attr!r}: {item.get('@id', locator)!r},")
            default = " = None" if nullable else ""
            attributes.append(f"    {attr}: {dtype}{default}")
        lines.extend(
            [
                "@dataclass(frozen=True, kw_only=True)",
                f"class {cls}:",
                f"    __record_set__: ClassVar[str] = {record.get('@id', pointer)!r}",
                "    __source_digest__: ClassVar[str] = SOURCE_DIGEST",
                "",
                *attributes,
                "",
                "    __field_refs__: ClassVar[dict[str, str]] = {",
                *field_refs,
                "    }",
                "",
                "",
            ]
        )
        return cls

    row = emit(target.record, target.identity, target.class_name)
    imports = ["from dataclasses import dataclass", "from typing import ClassVar, TypeAlias"]
    if needs_unknown:
        imports += ["from biotope.graph.sources import UnknownValue"]
    # Identity only: a JSON pointer would shift when an earlier record set is removed,
    # marking every later package stale for a change that did not touch it.
    identity = json.dumps({"id": target.identity}, separators=(",", ":"))
    preamble = [
        HEADER.rstrip(),
        RECORD_SET_MARKER + identity,
        "from __future__ import annotations",
        "",
        *imports,
        "",
        f"GENERATOR_VERSION = {GENERATOR_VERSION!r}",
        f"SOURCE_DIGEST = {revision!r}",
    ]
    inventory = [f"RECORDS: tuple[type, ...] = ({row},)", f"SourceRow: TypeAlias = {row}"]
    return "\n".join([*preamble, "", *lines, *inventory]).rstrip() + "\n"


def render_inventory(metadata: Path, root: Path, targets: Sequence[RecordSetTarget]) -> str:
    """Render the per-manifest inventory of every record set's registered contract."""
    relative = Path(os.path.relpath(metadata.resolve(), root.resolve())).as_posix()
    packages = sorted(target.package for target in targets)
    marker = json.dumps({"metadata": relative, "packages": packages}, separators=(",", ":"))
    body = [
        f"from . import {', '.join(packages)}" if packages else "",
        "",
        "",
        "CONTRACTS: tuple[SourceContract, ...] = (" + "".join(f"{name}.SOURCE, " for name in packages).rstrip() + ")",
    ]
    return (
        "\n".join(
            [
                HEADER.rstrip(),
                MANIFEST_MARKER + marker,
                f'"""Generated inventory of every record set described by {metadata.name}.',
                "",
                "Select participating contracts into SOURCES in graph/sources/__init__.py;",
                "generation does not choose pipeline scope.",
                '"""',
                "",
                "from __future__ import annotations",
                "",
                "from biotope.graph import SourceContract",
                "",
                *body,
            ]
        ).rstrip()
        + "\n"
    )


def _write_module(code: str, output: Path) -> Path:
    if output.exists() and not output.read_text(encoding="utf-8").startswith(HEADER):
        raise ValueError(f"{output} is authored code; choose a separate generated module")
    write_text_atomic(output, code)
    Path(importlib.util.cache_from_source(str(output))).unlink(missing_ok=True)
    return output


def package_root(metadata: Path, output: Path, package: str | None = None) -> Path:
    """Resolve the per-manifest package directory beneath a sources root."""
    # A module path here is the retired --out shape; fail loudly rather than
    # creating a directory named schema.py.
    if output.suffix == ".py" or output.is_symlink() or (output.exists() and not output.is_dir()):
        raise ValueError(f"{output} is not a directory; --out is the sources root, e.g. graph/sources")
    name = package or _slug(metadata.stem)
    if not name.isidentifier() or keyword.iskeyword(name) or name in RESERVED_NAMES:
        raise ValueError(f"{name!r} is not an importable package name; pass --package <name>")
    return output / name


@dataclass(frozen=True)
class PackageStatus:
    """One generated package's agreement with the manifest."""

    package: str
    path: Path
    state: str
    identity: str | None
    detail: str

    @property
    def severity(self) -> str:
        if self.state == "current":
            return "ok"
        # A leftover package is stale project code, not a broken contract.
        return "warning" if self.state in {"orphan", "renamed"} else "error"


def check_source_packages(metadata: Path, output: Path, package: str | None = None) -> tuple[PackageStatus, ...]:
    """Compare a manifest against its generated packages without writing."""
    root = package_root(metadata, output, package)
    data = read_metadata(metadata)
    targets = record_set_targets(data)
    known = {target.identity: target for target in targets}
    statuses: list[PackageStatus] = []

    inventory = root / "__init__.py"
    relative = Path(os.path.relpath(metadata.resolve(), root.resolve())).as_posix()
    if not inventory.is_file():
        statuses.append(PackageStatus("", inventory, "missing", None, "no generated inventory"))
    else:
        current = inventory.read_text(encoding="utf-8")
        owner = _marker(current, MANIFEST_MARKER, "metadata")
        if not current.startswith(HEADER):
            statuses.append(
                PackageStatus(
                    "",
                    inventory,
                    "authored",
                    None,
                    f"this path is now the generated inventory; move the package under {root}/<record-set>/, "
                    "or choose a different --out/--package",
                )
            )
        elif owner is not None and owner != relative:
            statuses.append(PackageStatus("", inventory, "conflict", None, f"generated from {owner}, not {relative}"))
        elif current != render_inventory(metadata, root, targets):
            statuses.append(PackageStatus("", inventory, "stale", None, "inventory does not match the manifest"))
        else:
            statuses.append(PackageStatus("", inventory, "current", None, ""))

    for target in targets:
        module = root / target.package / "schema.py"
        if not module.is_file():
            state, detail = "missing", "no generated module"
        else:
            current = module.read_text(encoding="utf-8")
            found = header_identity(current)
            if not current.startswith(HEADER):
                state, detail = "authored", "authored code occupies a generated module path"
            elif found != target.identity and not _positional(found, target.identity):
                state, detail = "conflict", f"holds record set {found!r}"
            elif current != render_source(data, target):
                state, detail = "stale", "does not match the manifest"
            else:
                state, detail = "current", ""
        statuses.append(PackageStatus(target.package, module, state, target.identity, detail))

    expected = {target.package for target in targets}
    if root.is_dir():
        for child in sorted(c for c in root.iterdir() if c.is_dir() and not c.is_symlink()):
            module = child / "schema.py"
            # Only generated packages are classified; authored helpers are project business.
            if child.name in expected or not module.is_file():
                continue
            current = module.read_text(encoding="utf-8")
            if not current.startswith(HEADER):
                continue
            found = header_identity(current)
            moved = known.get(found) if found else None
            if moved is None:
                detail = f"record set {found!r} is no longer described" if found else "unidentified generated module"
                statuses.append(PackageStatus(child.name, module, "orphan", found, detail))
            else:
                statuses.append(PackageStatus(child.name, module, "renamed", found, f"now generates {moved.package}"))
    legacy = root / "schema.py"
    if legacy.is_file():
        statuses.append(
            PackageStatus("", legacy, "conflict", None, "single-module layout; regenerate into per-record-set packages")
        )
    return tuple(statuses)


def generate_source_packages(
    metadata: Path,
    output: Path,
    package: str | None = None,
    statuses: Sequence[PackageStatus] | None = None,
) -> tuple[Path, ...]:
    """Generate one package per record set, creating missing project-owned files.

    Pass ``statuses`` from an immediately preceding ``check_source_packages`` call
    to avoid re-rendering every existing module. Each write refuses authored code
    on its own, so a supplied pre-flight only changes when generation stops.
    """
    root = package_root(metadata, output, package)
    for status in check_source_packages(metadata, output, package) if statuses is None else statuses:
        if status.state in {"authored", "conflict"}:
            raise ValueError(f"{status.path}: {status.detail}")
    data = read_metadata(metadata)
    targets = record_set_targets(data)
    name = root.name
    template = Path(__file__).resolve().parents[1] / "templates/graph/sources/_example/example_rows/loader.py"
    loader = template.read_text(encoding="utf-8")
    rendered = [(target, render_source(data, target)) for target in targets]
    created: list[Path] = []
    for target, code in rendered:
        directory = root / target.package
        created.append(_write_module(code, directory / "schema.py"))
        relative = Path(os.path.relpath(metadata.resolve(), directory.resolve())).as_posix()
        registration = f'''"""Project-owned source registration; generated record inventory stays current."""

from pathlib import Path

from biotope.graph import SourceContract

from .schema import RECORDS


SOURCE = SourceContract(
    name={json.dumps(f"{name}/{target.package}")},
    metadata=Path(__file__).resolve().parent / {json.dumps(relative)},
    generated=Path(__file__).with_name("schema.py"),
    records=RECORDS,
)
'''
        for filename, contents in (("__init__.py", registration), ("loader.py", loader)):
            authored = directory / filename
            if authored.exists() or authored.is_symlink():
                continue
            # Exclusive creation also preserves a file authored during generation.
            try:
                with authored.open("x", encoding="utf-8") as stream:
                    stream.write(contents)
            except FileExistsError:
                continue
            created.append(authored)
    created.append(_write_module(render_inventory(metadata, root, targets), root / "__init__.py"))
    return tuple(created)


def _regenerate_advice(metadata: Path, output: Path) -> str:
    """Name the command that refreshes this module, including its package."""
    command = f"run biotope source generate {metadata} --out <sources root>"
    if len(output.parents) < 3:
        return command
    root, folder = output.parents[2], output.parents[1].name
    package = "" if folder == _slug(metadata.stem) else f" --package {folder}"
    return f"run biotope source generate {metadata} --out {root}{package}"


def check_generated(metadata: Path, output: Path) -> None:
    """Reject a changed manifest, an orphaned record set, or a modified/stale module."""
    advice = _regenerate_advice(metadata, output)
    if not output.is_file():
        raise ValueError(f"{output} is absent; {advice}")
    current = output.read_text(encoding="utf-8")
    if not current.startswith(HEADER):
        raise ValueError(f"{output} is not a generated module; {advice}")
    identity = header_identity(current)
    if identity is None:
        raise ValueError(f"{output} is stale; it predates the current generator, so {advice}")
    data = read_metadata(metadata)
    target = next((t for t in record_set_targets(data) if t.identity == identity), None)
    if target is None:
        raise ValueError(f"{output} is stale; record set {identity!r} is no longer described by {metadata}")
    if current != render_source(data, target):
        raise ValueError(f"{output} is stale; {advice}, then review mappings")
