# Generated by biotope; do not edit. Regenerate with biotope source generate.
# biotope:manifest {"metadata":"../../../.biotope/datasets/study.jsonld"}
"""Every source package generated from study.jsonld, collected when imported.

Select sources in graph/sources/__init__.py; generation does not choose scope.
"""

from biotope.graph import collect_contracts


CONTRACTS = collect_contracts(__name__)
