# Generated by biotope; do not edit. Regenerate with biotope source generate.
"""Every source package under graph/sources, collected from each generated root when imported."""

from biotope.graph import collect_inventory


INVENTORY = collect_inventory(__name__)
