# Generated by biotope.graph; edit curated Croissant, then regenerate.
# biotope:record-set {"id":"example-rows"}
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, TypeAlias

GENERATOR_VERSION = '5'
SOURCE_DIGEST = '2eb90bb9524f15d56ff41c8327bee22e903201e3c54590f221c6859707128092'

@dataclass(frozen=True, kw_only=True)
class ExampleRows:
    __record_set__: ClassVar[str] = 'example-rows'
    __source_digest__: ClassVar[str] = SOURCE_DIGEST

    record_id: str | None = None
    collection_id: str | None = None
    value: float | None = None

    __field_refs__: ClassVar[dict[str, str]] = {
        'record_id': 'example-rows/record_id',
        'collection_id': 'example-rows/collection_id',
        'value': 'example-rows/value',
    }


RECORDS: tuple[type, ...] = (ExampleRows,)
SourceRow: TypeAlias = ExampleRows
