"""End-to-end CLI walkthrough: init -> describe -> propose-mapping -> build."""

from __future__ import annotations

from pathlib import Path

from click.testing import CliRunner

from biotope.commands.build import build
from biotope.commands.describe import describe
from biotope.commands.init import init
from biotope.commands.propose_alignment import propose_alignment as propose_alignment_cmd
from biotope.commands.propose_mapping import propose_mapping

FIXTURES = Path(__file__).parent.parent / "fixtures" / "croissant"


def test_full_walkthrough(tmp_path: Path, monkeypatch) -> None:
    runner = CliRunner()

    # 1. init
    r = runner.invoke(init, ["bcc-e2e", "--dir", str(tmp_path), "--no-git"])
    assert r.exit_code == 0, r.output
    project_dir = tmp_path / "bcc-e2e"
    monkeypatch.chdir(project_dir)

    # 2. describe
    r = runner.invoke(describe, ["--purpose", "Walkthrough test", "--entity", "genes"])
    assert r.exit_code == 0, r.output

    # 3. propose-mapping against the minimal Croissant fixture
    minimal = FIXTURES / "minimal.croissant.json"
    r = runner.invoke(
        propose_mapping,
        [str(minimal)],
    )
    assert r.exit_code == 0, r.output
    out_mapping = project_dir / "mappings" / "minimal.mapping.yaml"
    assert out_mapping.is_file()
    mapping_text = out_mapping.read_text()
    assert "# Review scaffold generated by `biotope propose-mapping`." in mapping_text
    assert "# - Sample rows: unavailable" in mapping_text

    # 4. build
    r = runner.invoke(build, [])
    assert r.exit_code == 0, r.output
    build_dir = project_dir / "build"
    assert (build_dir / "config" / "schema_config.yaml").is_file()
    assert (build_dir / "config" / "biocypher_config.yaml").is_file()
    assert (build_dir / "create_knowledge_graph.py").is_file()
    assert (build_dir / "mappings" / "minimal.mapping.yaml").is_file()

    # build emits a JSON report somewhere in stdout
    assert "project_dir" in r.output
    assert "schema_config" in r.output


def test_build_accepts_plain_yaml_mapping_name(tmp_path: Path, monkeypatch) -> None:
    runner = CliRunner()

    r = runner.invoke(init, ["bcc-e2e", "--dir", str(tmp_path), "--no-git"])
    assert r.exit_code == 0, r.output
    project_dir = tmp_path / "bcc-e2e"
    monkeypatch.chdir(project_dir)

    r = runner.invoke(describe, ["--purpose", "Walkthrough test", "--entity", "genes"])
    assert r.exit_code == 0, r.output

    minimal = FIXTURES / "minimal.croissant.json"
    plain_yaml = project_dir / "mappings" / "minimal.yaml"
    r = runner.invoke(
        propose_mapping,
        [str(minimal), "--out", str(plain_yaml)],
    )
    assert r.exit_code == 0, r.output
    assert plain_yaml.is_file()

    r = runner.invoke(build, [])
    assert r.exit_code == 0, r.output
    assert (project_dir / "build" / "mappings" / "minimal.yaml").is_file()


def test_build_prefers_mapping_yaml_when_plain_and_suffixed_both_exist(tmp_path: Path, monkeypatch) -> None:
    runner = CliRunner()

    r = runner.invoke(init, ["bcc-e2e", "--dir", str(tmp_path), "--no-git"])
    assert r.exit_code == 0, r.output
    project_dir = tmp_path / "bcc-e2e"
    monkeypatch.chdir(project_dir)

    r = runner.invoke(describe, ["--purpose", "Walkthrough test", "--entity", "genes"])
    assert r.exit_code == 0, r.output

    minimal = FIXTURES / "minimal.croissant.json"
    plain_yaml = project_dir / "mappings" / "minimal.yaml"
    suffixed_yaml = project_dir / "mappings" / "minimal.mapping.yaml"

    r = runner.invoke(propose_mapping, [str(minimal), "--out", str(plain_yaml)])
    assert r.exit_code == 0, r.output
    r = runner.invoke(propose_mapping, [str(minimal), "--out", str(suffixed_yaml)])
    assert r.exit_code == 0, r.output

    r = runner.invoke(build, [])
    assert r.exit_code == 0, r.output
    build_mappings = sorted((project_dir / "build" / "mappings").glob("*.yaml"))
    assert build_mappings == [project_dir / "build" / "mappings" / "minimal.mapping.yaml"]


def test_propose_alignment_defaults_to_project_alignment_yaml(tmp_path: Path, monkeypatch) -> None:
    runner = CliRunner()

    r = runner.invoke(init, ["bcc-e2e", "--dir", str(tmp_path), "--no-git"])
    assert r.exit_code == 0, r.output
    project_dir = tmp_path / "bcc-e2e"
    monkeypatch.chdir(project_dir)

    r = runner.invoke(describe, ["--purpose", "Walkthrough test", "--entity", "genes"])
    assert r.exit_code == 0, r.output

    minimal = FIXTURES / "minimal.croissant.json"
    a = project_dir / "mappings" / "a.mapping.yaml"
    b = project_dir / "mappings" / "b.mapping.yaml"
    assert runner.invoke(propose_mapping, [str(minimal), "--out", str(a)]).exit_code == 0
    assert runner.invoke(propose_mapping, [str(minimal), "--out", str(b)]).exit_code == 0

    r = runner.invoke(propose_alignment_cmd, [str(a), str(b)])
    assert r.exit_code == 0, r.output

    alignment_path = project_dir / "alignment.yaml"
    assert alignment_path.is_file()
    alignment_text = alignment_path.read_text()
    assert "equivalences:" in alignment_text
    assert "kind: same_node" in alignment_text
