# Generated by biotope.graph; edit curated Croissant, then regenerate.
# biotope:manifest {"metadata":"metadata.jsonld","packages":["example_rows"]}
"""Generated inventory of every record set described by metadata.jsonld.

Select participating contracts into SOURCES in graph/sources/__init__.py;
generation does not choose pipeline scope.
"""

from __future__ import annotations

from biotope.graph import SourceContract

from . import example_rows


CONTRACTS: tuple[SourceContract, ...] = (example_rows.SOURCE,)
